name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v3
       with:
        java-version: '11'
        distribution: 'adopt'
     - run: mvn --batch-mode --update-snapshots verify
     - run: mvn compile war:war
     - run: mvn clean package --file pom.xml
     - run: mkdir -p target/

     - name: Temporarily save war artifact
       uses: actions/upload-artifact@v2
       with:
        name: war-artifact
        path: ${{ github.workspace }}/target/*.war
        retention-days: 1
  deploy:
     runs-on: ubuntu-18.04
     needs: build
     steps:
      - uses: actions/upload-artifact@v1
        with:
           name: jar-artifact
           path: target/
      - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
